version: '3'
services:
    apache:
        build: .docker/apache
        container_name: doughnut_apache
        ports:
            - 8080:80
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - .:/home/wwwroot/doughnut_api
        depends_on:
            - php
        networks:
            - main

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: doughnut_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: doughnuts
            MYSQL_USER: dougnut_user
            MYSQL_PASSWORD: doughnut_password

    php:
        build: .docker/php
        container_name: doughnut_php
        volumes:
            - .:/home/wwwroot/doughnut_api
        depends_on:
            - mysql
        networks:
            - main

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: doughnut_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8081:80
        links:
            - mysql
        networks:
            - main

networks:
    main:
